### ISSUE TITLE
Gives EXC_BAD_ACCESS line 55 LLRoundSwitchKnobLayer.m

### ISSUE THREAD

**Issue by dimme** [LordLobo/LLRoundSwitch#1]
It suffers from the same problem as:

https://github.com/domesticcatsoftware/DCRoundSwitch/issues/10

and:

http://stackoverflow.com/questions/8457466/dcroundswitch-gives-exc-bad-access-when-using-arc

**Comment by LordLobo** [comment]
So far I've only finished transcribing the original code, so my next move is to complete the test suite.

Thanks for the heads up.

**Comment by LordLobo** [comment]
Give my last check-in a shot, this should have the right memory profile.  

I need to give it a deeper analysis however, not quite as perfect as I'd like.

**Comment by dimme** [comment]
It's the same change as I proposed in my pull request: https://github.com/LordLobo/LLRoundSwitch/pull/2/files

However, afterwards I realized that it gave the same error.

The only solution that works that I found so far is to deactivate ARC on this specific file.

**Comment by LordLobo** [comment]
My changes are a bit different (note the collection changes in drawInContext()), and the static analyser doesn't find a leak now.  Instruments is being a jerk to me however if you can provide a 'steps to reproduce' for this crash that would be helpful.

I was able to see the crash in the demo suite before my fix, but not in this version.

**Comment by LordLobo** [comment]
Ok I just uploaded a new version of the Demo Suite - if you click switch4 (the upper-right-most switch) it will hide switch1.  You can break on lines 50 and 60 in LLRoundSwitchKnobLayer.m and with Instruments open it does not find any leaks, even though those renders are called every time (several times).

**Comment by LordLobo** [comment]
closing issue - no new reports
